/**
 * @module generated_types
 *
 * Auto-generated TypeScript types from JSON schemas.
 * DO NOT EDIT MANUALLY - Run `deno task codegen` to regenerate.
 *
 * @generated
 */

// =============================================================================
// Generated Types from plugin.schema.json
// DO NOT EDIT - This file is auto-generated by scripts/codegen.ts
// =============================================================================

/**
 * Schema for deno-dist plugin metadata definitions
 */
export interface PluginMetadataSchema {
  /** Unique plugin identifier (kebab-case, e.g., 'deno-to-node') */
  readonly id: string;
  /** Human-readable plugin name */
  readonly name: string;
  /** Plugin version (semver) */
  readonly version: string;
  /** Brief description of what the plugin does */
  readonly description: string;
  /** Target runtime this plugin produces output for, or 'any' for lifecycle-only plugins */
  readonly targetRuntime: "deno" | "node" | "bun" | "any";
  /** Author or maintainer */
  readonly author?: string;
  /** License identifier (SPDX) */
  readonly license?: string;
  /** Repository URL */
  readonly repository?: string;
  /** Plugin homepage or documentation URL */
  readonly homepage?: string;
  /** Which phases this plugin implements. If not specified, all implemented methods are used. */
  readonly phases?: readonly ("preprocess" | "transform" | "postprocess" | "setup" | "release")[];
  /** Plugin IDs that this plugin must run after */
  readonly dependencies?: readonly string[];
  /** Plugin IDs that cannot be used together with this plugin */
  readonly conflicts?: readonly string[];
  /** Whether this plugin's phases can safely run in parallel with other parallelizable plugins */
  readonly canParallelize?: boolean;
  /** Tags for plugin discovery and categorization */
  readonly tags?: readonly string[];
  /** JSON Schema for plugin-specific options */
  readonly options?: Record<string, unknown>;
}

// =============================================================================
// Generated Types from distribution.schema.json
// DO NOT EDIT - This file is auto-generated by scripts/codegen.ts
// =============================================================================

export interface InlinePluginConfig {
  /** Plugin identifier */
  readonly id: string;
  /** Plugin-specific options */
  readonly options?: Record<string, unknown>;
  /** Whether this plugin is enabled */
  readonly enabled?: boolean;
}

export interface TestConfig {
  /** Command to run tests */
  readonly command?: string;
  /** Setup commands to run before tests */
  readonly setup?: readonly string[];
  /** Test timeout in milliseconds */
  readonly timeout?: number;
  /** Environment variables for testing */
  readonly env?: Record<string, string>;
  /** Whether tests are enabled for this distribution */
  readonly enabled?: boolean;
}

export interface PublishConfig {
  /** Registries to publish to. Supports multiple registries per distribution. */
  readonly registries?: readonly (string | RegistryConfig)[];
  /** DEPRECATED: Use 'registries' instead. Single registry to publish to. */
  /** @deprecated */
  readonly registry?: string;
  /** Whether to generate provenance attestations */
  readonly provenance?: boolean;
  /** Access level for the published package */
  readonly access?: "public" | "restricted";
  /** Custom publish command (overrides registry-specific commands) */
  readonly command?: string;
  /** Whether to perform a dry run without actually publishing */
  readonly dryRun?: boolean;
}

export interface RegistryConfig {
  /** Registry identifier or plugin ID (e.g., 'npm', 'jsr', 'github-release') */
  readonly id: string;
  /** Registry-specific options */
  readonly options?: Record<string, unknown>;
  /** Whether this registry is enabled */
  readonly enabled?: boolean;
}

export interface ReleaseNotesConfig {
  /** Path to release notes template file */
  readonly template?: string;
  /** Method to generate release notes */
  readonly generate?: "conventional" | "changelog" | "git-log" | "custom";
  /** Commit types to include in generated notes */
  readonly include?: readonly string[];
  /** Commit types to exclude from generated notes */
  readonly exclude?: readonly string[];
}

/**
 * Schema for a single distribution target configuration
 */
export interface DistributionConfigSchema {
  /** Target runtime identifier */
  readonly runtime: "deno" | "node" | "bun";
  /** Runtime versions to test against (e.g., ['18', '20', '22'] for Node.js) */
  readonly versions?: readonly string[];
  /** Plugins to apply. Use '@this' to control custom script ordering. */
  readonly plugins?: readonly (string | InlinePluginConfig)[];
  /** Path to custom preprocess script */
  readonly preprocess?: string;
  /** Path to custom transform script */
  readonly transform?: string;
  /** Path to custom postprocess script */
  readonly postprocess?: string;
  /** Path to custom setup script */
  readonly setup?: string;
  /** Path to custom release script */
  readonly release?: string;
  /** Template file mappings (name -> file path) */
  readonly templates?: Record<string, string>;
  /** String replacement patterns (pattern -> replacement) */
  readonly replacements?: Record<string, string>;
  readonly test?: TestConfig;
  readonly publish?: PublishConfig;
  readonly releaseNotes?: ReleaseNotesConfig;
}

// =============================================================================
// Generated Types from config.schema.json
// DO NOT EDIT - This file is auto-generated by scripts/codegen.ts
// =============================================================================

export interface CiConfig {
  /** CI provider for workflow generation */
  readonly provider?: "github" | "gitlab" | "codeberg" | "custom";
  /** Directory for CI workflow files (defaults to provider-specific path) */
  readonly workflowsDir?: string;
  /** Whether to generate test workflows */
  readonly testWorkflow?: boolean;
  /** Whether to generate release workflows */
  readonly releaseWorkflow?: boolean;
  /** Main branch name for CI triggers */
  readonly branchName?: string;
  readonly concurrency?: {
    /** Concurrency group pattern */
    readonly group?: string;
    /** Whether to cancel in-progress runs */
    readonly cancelInProgress?: boolean;
  };
}

/**
 * Supported runtime identifiers
 */
export type RuntimeId = "deno" | "node" | "bun";

/**
 * Pipeline phase identifiers
 */
export type PhaseId = "preprocess" | "transform" | "postprocess" | "setup" | "release";

export type PluginReference = string | {
  /** Plugin identifier */
  readonly id: string;
  /** Plugin-specific options */
  readonly options?: Record<string, unknown>;
  /** Whether this plugin is enabled */
  readonly enabled?: boolean;
};

/**
 * Schema for deno-dist configuration in deno.json
 */
export interface DistConfigSchema {
  /** Package name (used for publishing) */
  readonly name?: string;
  /** Package version (semver) */
  readonly version?: string;
  /** Output directory for all distributions (relative path, no '..') */
  readonly distDir?: string;
  /** Named distribution configurations */
  readonly dist?: Record<string, DistributionConfigSchema>;
  /** Package metadata including dist-specific settings */
  readonly metadata?: {
    readonly dist?: {
      /** Custom template variables available as @{varName} */
      readonly scope?: Record<string, string>;
      /** Default plugins to apply to all distributions */
      readonly defaultPlugins?: readonly string[];
      readonly ci?: CiConfig;
    };
  };
}

// =============================================================================
// Type Guards and Constants
// =============================================================================

/**
 * Build phase identifiers (operate on code).
 */
export type BuildPhaseId = "preprocess" | "transform" | "postprocess";

/**
 * Lifecycle phase identifiers.
 */
export type LifecyclePhaseId = "setup" | "release";

/**
 * Target runtime including 'any' for lifecycle-only plugins.
 */
export type TargetRuntime = RuntimeId | "any";

/**
 * Check if a value is a valid RuntimeId.
 */
export function isRuntimeId(value: unknown): value is RuntimeId {
  return value === "deno" || value === "node" || value === "bun";
}

/**
 * Check if a value is a valid PhaseId.
 */
export function isPhaseId(value: unknown): value is PhaseId {
  return (
    value === "preprocess" ||
    value === "transform" ||
    value === "postprocess" ||
    value === "setup" ||
    value === "release"
  );
}

/**
 * Check if a value is a build phase.
 */
export function isBuildPhase(value: unknown): value is BuildPhaseId {
  return value === "preprocess" || value === "transform" || value === "postprocess";
}

/**
 * Check if a value is a lifecycle phase.
 */
export function isLifecyclePhase(value: unknown): value is LifecyclePhaseId {
  return value === "setup" || value === "release";
}

/**
 * All valid runtime identifiers.
 */
export const RUNTIME_IDS: readonly RuntimeId[] = ["deno", "node", "bun"] as const;

/**
 * All valid phase identifiers.
 */
export const PHASE_IDS: readonly PhaseId[] = [
  "preprocess",
  "transform",
  "postprocess",
  "setup",
  "release",
] as const;

/**
 * Build phases (operate on code).
 */
export const BUILD_PHASE_IDS: readonly BuildPhaseId[] = [
  "preprocess",
  "transform",
  "postprocess",
] as const;

/**
 * Lifecycle phases (setup and release).
 */
export const LIFECYCLE_PHASE_IDS: readonly LifecyclePhaseId[] = ["setup", "release"] as const;
